# Generated by Django 6.0.2 on 2026-02-21 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contact Submissions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlanMyEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('event_occasion', models.CharField(max_length=255)),
                ('event_location', models.CharField(max_length=255)),
                ('event_date', models.DateField()),
                ('venue', models.CharField(blank=True, max_length=255)),
                ('theme_of_decor', models.CharField(blank=True, max_length=255)),
                ('expected_guests', models.IntegerField(blank=True, null=True)),
                ('budget', models.CharField(blank=True, max_length=100)),
                ('food_nigerian_dishes', models.BooleanField(default=False)),
                ('food_oriental_dishes', models.BooleanField(default=False)),
                ('food_continental_dishes', models.BooleanField(default=False)),
                ('food_desserts', models.BooleanField(default=False)),
                ('food_finger_foods', models.BooleanField(default=False)),
                ('food_other', models.BooleanField(default=False)),
                ('drinks_alcoholic_cocktails', models.BooleanField(default=False)),
                ('drinks_non_alcoholic_cocktails', models.BooleanField(default=False)),
                ('drinks_alcoholic', models.BooleanField(default=False)),
                ('drinks_non_alcoholic', models.BooleanField(default=False)),
                ('drinks_red_wine', models.BooleanField(default=False)),
                ('drinks_champagne', models.BooleanField(default=False)),
                ('drinks_other', models.BooleanField(default=False)),
                ('beverages_tea', models.BooleanField(default=False)),
                ('beverages_coffee', models.BooleanField(default=False)),
                ('beverages_cappuccino', models.BooleanField(default=False)),
                ('beverages_hot_chocolate', models.BooleanField(default=False)),
                ('beverages_other', models.BooleanField(default=False)),
                ('service_event_coordination', models.BooleanField(default=False)),
                ('service_marquee_rental', models.BooleanField(default=False)),
                ('service_photography', models.BooleanField(default=False)),
                ('service_videography', models.BooleanField(default=False)),
                ('service_live_band', models.BooleanField(default=False)),
                ('message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Plan My Event',
                'verbose_name_plural': 'Plan My Event Submissions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RequestQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('service', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Request Quote',
                'verbose_name_plural': 'Request Quote Submissions',
                'ordering': ['-created_at'],
            },
        ),
    ]
